[package]
name = "maxiscript"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
hex-conservative = "0.3.0"
chumsky = "0.10.0"
ariadne = "0.5.1"
bitcoin = "0.32.5"
log = "0.4.27"
env_logger = "0.11.8"

[dev-dependencies]
bitcoinconsensus = "0.106.0"
